#name: Push to Docker
#
#on:
#  release:
#    types: [ published ]
#
#jobs:
# # Publish Dockerfile to docker hub
#  push_to_docker_registry:
#    name: Publish to Docker hub
#    runs-on: ubuntu-latest
#
#    # Needs build phase
#    needs: [build]
#
#    steps:
#
#      - name: Check out the repository
#      - uses: actions/checkout@v2
#
#      - name: Push to Docker hub
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: ${{ secrets.DOCKER_REPO }}
#          build-args: |
#            BASE_IMAGE=hey # TODO
#          tag_with_ref: true
#          file: actions.Dockerfile # TODO
#
#
#
#
##  - name: Read server.port from Properties file
#      #   id: read_property_port
#      #   uses: christian-draeger/read-properties@1.0.1
#      #   with:
#      #     path: './docker.properties'
#      #     property: "server.port"
#
#      # - name: Read server.host from Properties file
#      #   id: read_property_host
#      #   uses: christian-draeger/read-properties@1.0.1
#      #   with:
#      #     path: './docker.properties'
#      #     property: "server.host"
#
#      # - name: echo port
#      #   run: echo ${{ steps.read_property_port.outputs.value }}
#
#      # - name: echo host
#      #   run: echo ${{ steps.read_property_host.outputs.value }}